artists = [
    {"name": "Bad Bunny", "followers": 48000000, "description": "Reggaeton and Latin trap artist", "country": "Puerto Rico"},
    {"name": "Karol G", "followers": 55000000, "description": "Latin pop and reggaeton singer", "country": "Colombia"},
    {"name": "Shakira", "followers": 90000000, "description": "International Latin pop artist", "country": "Colombia"},
    {"name": "J Balvin", "followers": 52000000, "description": "Global reggaeton artist", "country": "Colombia"},
    {"name": "Maluma", "followers": 63000000, "description": "Latin urban pop artist", "country": "Colombia"},
    {"name": "Rosalía", "followers": 27000000, "description": "Experimental flamenco pop artist", "country": "Spain"},
    {"name": "Feid", "followers": 13000000, "description": "Reggaeton and urban pop singer", "country": "Colombia"},
    {"name": "Rauw Alejandro", "followers": 18000000, "description": "Latin pop and reggaeton artist", "country": "Puerto Rico"},
    {"name": "Ozuna", "followers": 22000000, "description": "Reggaeton and Latin trap artist", "country": "Puerto Rico"},
    {"name": "Anitta", "followers": 65000000, "description": "Pop and Brazilian funk artist", "country": "Brazil"},

    {"name": "Taylor Swift", "followers": 280000000, "description": "Pop and country-pop singer-songwriter", "country": "United States"},
    {"name": "Ariana Grande", "followers": 380000000, "description": "Pop and R&B vocalist", "country": "United States"},
    {"name": "Drake", "followers": 145000000, "description": "Hip hop and R&B artist", "country": "Canada"},
    {"name": "The Weeknd", "followers": 120000000, "description": "Alternative R&B and pop artist", "country": "Canada"},
    {"name": "Billie Eilish", "followers": 120000000, "description": "Alternative pop singer-songwriter", "country": "United States"},
    {"name": "Dua Lipa", "followers": 90000000, "description": "Dance pop artist", "country": "United Kingdom"},
    {"name": "Ed Sheeran", "followers": 48000000, "description": "Pop and folk singer-songwriter", "country": "United Kingdom"},
    {"name": "BTS", "followers": 76000000, "description": "K-pop boy band", "country": "South Korea"},
    {"name": "Blackpink", "followers": 94000000, "description": "K-pop girl group", "country": "South Korea"},
    {"name": "Post Malone", "followers": 26000000, "description": "Hip hop and pop artist", "country": "United States"},

    {"name": "Daddy Yankee", "followers": 50000000, "description": "Pioneer reggaeton artist", "country": "Puerto Rico"},
    {"name": "Nicky Jam", "followers": 42000000, "description": "Reggaeton and Latin pop artist", "country": "United States"},
    {"name": "Luis Fonsi", "followers": 34000000, "description": "Latin pop singer", "country": "Puerto Rico"},
    {"name": "Camilo", "followers": 28000000, "description": "Romantic Latin pop singer", "country": "Colombia"},
    {"name": "Sebastián Yatra", "followers": 29000000, "description": "Latin pop and ballad singer", "country": "Colombia"},
    {"name": "Morat", "followers": 12000000, "description": "Latin pop rock band", "country": "Colombia"},
    {"name": "Manuel Turizo", "followers": 16000000, "description": "Latin pop and urban artist", "country": "Colombia"},
    {"name": "CNCO", "followers": 9000000, "description": "Latin pop boy band", "country": "United States"},
    {"name": "Romeo Santos", "followers": 21000000, "description": "Modern bachata singer", "country": "United States"},
    {"name": "Prince Royce", "followers": 16000000, "description": "Bachata and Latin pop singer", "country": "United States"}
]
